---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgAtcgxJaiydNoHHNit1emZIi9xCLaJn/STivVNfuKHOr1aCztH6AmsZntjPNnbKhEwTgOES8Nk0X5CWXNltY58FJCqFKGB2U6RiPzZaR7Em8AR4vZ1NNCaMydSh3IdH0+FmezmB69MX0TFCS99lF7MMQcOaiPtZbPlHVvLOrln8isYLDP8ZNAyXI9fyOLrF+jY+ZDkKO+JUFmrujdW5g6XSkVJ7RLspPhH8wM4csSriTZzpMawh4qcFpkHM0Sl4z1gh65691IG6oJuXx+U2Og7BfYksdQTuuhekh95EOKoRfw40OYQPh6NvGrfUbDU8U3kGA7c0poPvaQIPYlZO2SKvQh44TEHtrowm13A2kaYhbH/Zdzeu9kYiGeTZ3ES9e7GaEuhgFQh8zNPExf1AFXX8q2hjfiMWq0TJ91GLaEwXdOIK2dK3JVspY1vjmqG18QN8MB2LRT8XKFKkXBDU2+S5CGnERA/SQ9JIVWkc0m3bc+xG14rAkECG09VGTFg1H3n+Kuxx0sjiRU+1gnWBA71rF9xubf2ymH/RetjVpDUfkbRoJ52iaUqCEql5nHlY4zirO0mOBdIKXoKmVcXP8XjrDpJDM1U4GHtK0ixPh54V/qcfkJkrecJ84LXNW/sJz9l1E8i9lxDOSH52xyGfqxchUdwuyffwTHefJnGYEiWl7lMCfP5wnKW+GewadaH4VjOro62l8PNo8P/3WpnAG5NLCEJOfcC3G/k7iWBP9v7KcEdPceJFtOUKYhGBNbvYsOG+gw43yqBekjobNlAkiO87zx/4BwcvbIDYgPi7ALe/f2HHF3QzL8raJjBM8yIpcT3ZP/gvujbVFbnBW9FveimIcEZ1lHDycBN1YqeTp38pHPLQXjoC5fERe0ZrHn9E2KCOkGq64NldF9qMU269WW8RlEVsdnXUHGDcR6BFKGxit9kbjXs5aix3
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: dev
    type: kubernetes.io/dockerconfigjson
