---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgB9x714afchhFpAbIrh9ZGWMggYfr5su3MEdFSeDip+2x3YfFajQGo/L5UvuQfRlgEFxejCG4l2SPPFemhnfgzuuD0TGneyM2aZf/SZ77ltzMFrLR2cisj2IXQcHSbcaW+pHTGBJE2qQH3YytpxWOny5F4j36YRM9sSHCvktbrDxnpXSt6jJb8GqzXN5iatHM7RyDbEU/BGQZ/d+7ciemjHbV81lPEw6z+l/gHjMmX3rxFDAOWZyGDMo3ZnTNYLJOfUMTtSZgYvLZMGftrVUICKAwMre1O55VT9M/bp2g2C5VsBTV3rs/3zA6tkHo0fdIKSUhIaY5PedaTgEE+dF9dAfGXk7bGxi0+9ttsMVtGcxARwuV3g7cObviwSU/zSFIKFHMRGyaVhCDKPoAAy0degVyyRZr9kzo0DOFSZRhIs0Hc8npO399OmXkMAmjX4c3hroMs/uTaStd6f4Z8TPkJV5ZuT8x+EudK/4j9dqRjkNYbFVSTRehz0+B8QNtVtn0GIRwCkVbgHS+pPflR/C6Fqse2MoZ2OCtY+BtfQNYCy0XtQSihtAGrN/jl+jMqkKlIv4f7ntEbUuk82Yxz1JlobuP7BP9dfMIigIawicJ8g9hS5jMlDZ4SFo4V5VPQqhfCd6YgLKueSdkSTjNp1wbRHD7yZctB5miegu5QCDcr13q6pjhU0/Tcvj+1HXEzODWfoFdLyO1SGmD4zIhTUi6eZwrCyQxwpbV8mLjhcJDTVi3GbOI8vi469dbKsHN05d22Uga6JiDKoX6vof5xmHPPtVabwUKEMlYYqma9MhmKuY0FTBZ7+OMHqfegncEHHmsZLnfgmc6Rkq/8fmfc7oFOTX3Pjr/R+5+tJ7OWV3x/en87z1Hl09ub0t6qe9g3f47/D1mZzUDhyej7RdIb9vORTifuiY1oMhZIU1d7ptZ9DZ2nm6d7U1Ckb
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: dev
    type: kubernetes.io/dockerconfigjson
