---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: prod
spec:
  encryptedData:
    .dockerconfigjson: AgARSHd3kRKJs2Ze+T36k47sUtAiFU8QdU5JUsROlG/t6ENwmVL8S1FfaukNKgfFhdu9Wy89hRP5CRgtdyNDQVzIqQH4szXem7Uk2v47lyS4DOrIyNNRu0N6lpqP90IHRHXJP792gTeO8/bqfTCMVdvsHJw9bYT9dwh/tT5NdvxsX4F4Rvb+SeX6+CpcMErAFpecH1s6KxSWxENxJ4lfncVao1sHkRdPxhq3r/e289ezjI17h+qlfkGKnzrsz/zSAgn3zgRQO/FHEOlzAsmBPc6nwODiSyClqX3vvAY0iKR+DXf7nxrtvoZzJ6PXKbUCIqk90X+u0JyVG7SCa8Lm1QYgTHd7ok6+D81JYVpYHYpuMFNypLb75ZvvmNCMJ2U55RrAXxTDXK5x5A097KEOiinfGbp1D2qs+1DhzrNuXD2RFLya23sp8jdDNKMIx5YZxPPfiJ/e6K/GNhSB32ygtBSicgAVSxBY73NkorNNHqICCC4LH7VDHqLEMS90CTv4mFvGkxEQz2BOsh/Qnh4/v0RnUh0wsOBZVSr01w5NRY7aefYJIcoCUCxPApuc08sKMIRYbYZpdAzcqvXIHuXxtJaLjRnST4rXpTdFBVdzQCFAldMw0/sD3MyPNLYz0zDIpggQGxWFmq9hoLKooaYkRa8kJauY2dCmoG+dxSEoUv5Mi6UpuvwFFXoEe+3NY8qGIlS8HtOyGZKQhnwGk8jJszuVMGLFQBg6Ir1NfEyvrfPsYBPWvB8DlOIs8Pd2E7pVdpgz0S/R4CzyaoqDYoklfnmkTUZOXYz2liOsl9b6w+ABRWzrv2vUKvCzlhpzecN/b8kMugfhzvG9RW/iHytSzND2gPUNXwpJQ+PrdSl7F0Ao/2CnJlkOqRev6gmkwTzMLsqMw87a+TlLMyijKrORbbC+vlIiNM0qUmc3Bwf1ltDWoaWMJXCoLqzt
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: prod
    type: kubernetes.io/dockerconfigjson
