apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: 35.2.0
    helm:
      valuesObject:
        deployment:
          replicas: 1
        service:
          type: LoadBalancer
          annotations:
            metallb.universe.tf/loadBalancerIPs: "10.0.0.10"
        ports:
          web:
            redirections:
              entryPoint:
                to: websecure
                scheme: https
          websecure:
            tls:
              enabled: true
        providers:
          kubernetesCRD:
            allowCrossNamespaceReferences: true
          kubernetesIngress:
            allowCrossNamespaceReferences: true
        logs:
          general:
            level: INFO
          access:
            enabled: true
        ingressClass:
          enabled: true
          isDefaultClass: true
          name: traefik
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 300Mi
            cpu: 500m
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
