apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../../base/openclaw
  - ingress.yaml
  - ../../../secrets/prod/regcred-sealed.yaml

images:
  - name: ghcr.io/surfside-labs/openclaw
    newTag: main-94730a3
