---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: prod
spec:
  encryptedData:
    .dockerconfigjson: AgB4BsixQEdzwBUQlvZg74/giUgoL5p6CVyxEybvc9mMqgbdKbx8NvnzVPAhprmhKY9hAxHz6frWfk+TnBd3Yy/3Y30+GjbZET47Qap082hVla1u3VvoQbF7Lhghg24lMxgqy/1YIL9ZsMz9W1gSUPjnlMoO/YBqgI7Yy0Dp4IijQOW/97adqAN6lCEUVD3VoXocK7wpt8M2P88lvmEciA73jQBpdtOIX2Wu3LYjGx5W+SyqY2OBsDPTX6DiflY0IO+cJ37ofy5kvQpBnxPZ0ZHBpKK6OQv5dTiwlUPSTOKYbRI86kpRsPADxCIhlUvGFLS2DouuYPISVQ1Gw+/YZDCTmJ09eQRTFuTK+T22cRvV/VG107Zx1bRncGPwokl4wWDdQr8FaI6wjBAMZrXoPMzDpFW84nj0xvhJS2RQ/JRKkGadW3KBvoQkmknQL1CZEVHZxKP6baXHj9mWUPnog5uq56OkGClccj3q0kuZYdnhElUepzZxAAmpJI+6np9VA1I9fSa//nDJIB3ICVDvADrfTX6in30LD0HHLT1Y7bz23sh09cLDfvjlNziC9esykQK6ICP2XKoZHX5gUQ1dya5P+OX1KZD7c95MS8qkMMOaMPjp9DwPy8V01idNgPcBHfPp4pq8z1x0R1wMh4M34z9dTfELd3sH/h9RM7tFj5gZUv09RYFJvbSETQX+1nNRwNpFHs3iVK1tWDADgPkSxi6xeBDfX5/4iPkbO04u1qTadV5vgKRxInpOjvswlPTSmIb8Qz5cBFPU0IieXFoMaBn9faBndvzsNP3GBSs5ILpuXv8lvn2CNzvKR1D6Kpjb2x5ryKTJ3n7z+ewMlp+WKlBKLPcSwZe0IIvGysco3iocGZTNArrxLrji6gV78ghFAeRLlyf8wyBCscDFhXzLizbaztvhyvknP89zw0K6Uv/eTbJTrwVVpyCv
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: prod
    type: kubernetes.io/dockerconfigjson
