---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: prod
spec:
  encryptedData:
    .dockerconfigjson: AgAiNT2Wdo36Dx8sjtlHOlE3zQi0NmJMT+bj+RgL3GTACOp331idrMdPkD0RtyQaPPTzepOqH/DMCRvHZad9l9FAceQlzk2mNL7mOogdZy3m4qoE07KD2FBP26d7FYMasXEEcF7W0zIGpON46xfGmd65SbWShz+dhO+cSCZKTFL6sPc62nnUf5yiBDWwI7Wg8SB6Jib6ZbKm492YTsmBiClLBbXLXJ+QsmxL4UoAZK/lXYc39VrMF3T9gQiDkFhWsxkWYNM5tSSLHYgcCtPbpsyBeGG7CKOvp6cI0r7zo43wCZHrsFC24WvIdmGXPCpEVw+Aj2+uhhOt71CYHb8upUx8Tk/zYajJQt0xpXrkmtSVrbUXyxW/mZCHPDZ7+5yGjc6TgL2LimtizxIKUTLj5I0B5yu+qae6y4HtrDe9XSD8mzl/V2D4mebajE/mF/C6s7XHi7TMYMbMTsrTjVOFT2xCJoJLN3SGGAtRp6VUvdKU3W63aj4GyqnWRnVDp+ovK7M4g9eSVwYNonXzmAcrrKFfedQQF6xrcz9eXSMnBoHlLtWL/yWkTz0P5rdT960zltMXQnmolhNF/wyoIFgOrsbgMLLxxkBA3JrITcsJ5vHq+gwFpQz5QltClqZBJYOlnL07TodtzAoF3gXwMXiFMrrqpQZ1CPg/2nINqhhVWNQHyi028elNlAfs9wnaEpDAJELhyGj7Rhsax+Xxiju2hTSQpOAzU/MXS9DbDx3jbewCrMCz5OPu2SggO+zlFMYVzCn/wki/fz86qDs+GdBbvW51PoUvfD7NnmgMeEWRJoCxoOF0/875F7p0hEzegMhJLq0BtUT4rF6jcZ+bQ3HKGz/pZSqF8zb/96BsVahXDbX1TjH4SPWxI3J0CLIGDniZIxBrn2Qy4Q5vwJOZArdgc7NB17IXruAfblUGglBhQ0xEAo71F+HfYm0e
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: prod
    type: kubernetes.io/dockerconfigjson
