---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgBOIumQzPQ71xzJpp1UPl/MFa+c6PGKCLMLEpF2RaEuH8jRO1ExQb/zhoQT7mpeqj2E0XNUlYdg9v/sFWmicrPvSZHP4We7WG8kMVgT1soHBW+7PkRV7koFcErmKFN3fF+TntM9TRFJv9QqFBbPaX9XytT50+gQBbavsM6j/+hhnrEUED6IpRCrY3NKsHHPxB6S0T28VNC+6PkQTNdevUk9Rv6FFEIC2MGQA00nlIbsFqzZtxqV2EvfxFwzMBAKtQ+TGcRv+xcQUEqoPFpBxJek7sIZ6Pval4oaOz4OWAVzAqkB0EfdZPubFRcpbrXi3ToKoXf9uqK330Dh+9Zpwk1lzQCtnZcdd8jJt9q9QWc2YWIoLQR+wWq8A2XdOXWBrpD7icPlsRwjYgX8M2Caf6KRVO4B6Ciq6lVwIgPYBU0ukqJLXhlKwKs6AEbz5racT59KsqoG6BPFLInekAfhsJ/KlhFRvx8d3MqGGlmOPUqV1BxAY/bnm9GMyxdbw/qgTORoiuydyJqdEs7s01aejxuGqBkAFQkADgLHWj+M3Xf0hIg1S50ApMTnitakBPcJqTrpWa2jO7YMR7vQXqt8DcNhbhh4Usbg+8Dn6H9cskxphx9EmP0dAlag0AXMOuC2LL8GTl+wSQWvu4dxBkgVhlj60qr7p9x1yFBKm9NpQajoyfFYXtFCxEyia0Aa38gtX+/mMbXMTKmNDy3PFTnDv8O3cnWXngM/U/yKeqDXK9Uid3jH2/+t0Q3sLWxGaemxP/Etcra4kNxwKy7v/VG6sQVRS3IlZLprb2wJwxidYeYbGfeIZUmj3QyK5nOi46KiJJox+/UweShMpwi2tlOG7DK0Q3qrh/SD7X93sgrRRT7qi6VhBJr8NWiuXfoMrPyDhD1HD1YN0CeFyF5yoa9K5Zd3D5rW/y++ywys6KpKshfdCVgNVaYbiD33
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: dev
    type: kubernetes.io/dockerconfigjson
